name: CI/CD and Docker
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      # 1. Lấy source code từ GitHub
      - name: Checkout source code
        uses: actions/checkout@v4
    # 2. Chuẩn bị môi trường build Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
# 3. Đăng nhập Docker Hub (dùng GitHub Secrets)
      - name: Login to Docker H
        uses: docker/login-action@v3
        with:
          username: ${{khoe265}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: khoe265/it4409-sample:staging
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-and-p
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /opt/express-app
            docker compose pull
            docker compose down
            docker compose up -d